# Generated by Django 4.2.5 on 2023-10-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_alter_donation_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
