# Generated by Django 4.2.5 on 2023-10-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_donation_delete_charity'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.CharField(default='123@gmail.com', max_length=100),
        ),
    ]
